[package]
name = "sirula"
version = "0.0.1"
authors = ["Dorian Rudolph"]
edition = "2018"

[dependencies]
freedesktop_entry_parser = "1.1.0"
locale-types = "0.4.0"
libc = "0.2.74"
gtk-layer-shell = "0.2.2"
gtk = { version = "0.14.1", features = ["v3_22"] }
gio = "0.14.6"
gdk = "0.14.2"
pango = "0.14.3"
gdk-pixbuf = "0.14.0"
glib = "0.14.8"
futures = "0.3.5"
fuzzy-matcher = "0.3.5"
xdg = "2.2.0"
serde = "1.0.114"
serde_derive = "1.0.114"
toml = "0.5.6"
regex = "1.4.2"

[profile.release]
lto = true
